apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: combative-silverfish-java-quarkus-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/combative-silverfish-java-quarkus